Topic/t928 015.diff.end of buffer
AdaCore/ada_language_server pull request #565
Opened 2020-10-12 14:01 UTC by AdrienBoulanger

Add a test

2020-10-12 18:17 UTC, godunko approved these changes

2020-10-12 18:18 UTC, godunko commented
Thank you!

2020-10-13 07:39 UTC, godunko requested changes

2020-10-13 07:39 UTC, godunko commented on testsuite/ada_lsp/T928-015.formatting.end_of_buffer/test.json
> +                  "uri": "file:///home/boulanger/adacore/example/T928-015/ui.ads"
Should $URI{ui.ads} be used here?

2020-10-13 09:29 UTC, AdrienBoulanger commented on testsuite/ada_lsp/T928-015.formatting.end_of_buffer/test.json
> +                  "uri": "file:///home/boulanger/adacore/example/T928-015/ui.ads"
Good catch

2020-10-13 11:12 UTC, godunko approved these changes

2020-10-13 12:42 UTC, merged