SA11-038 Improve Refactoring Rename
AdaCore/ada_language_server pull request #591
Opened 2020-12-09 14:09 UTC by joaopsazevedo

The existing rename funcitonality was replaced by Laltools' one.
An error message is return if it is detected that the rename operation will
cause problems.
Added one test for a name collision problem.
Output of rename tests with the changes required were sorted by line number.

2020-12-10 11:23 UTC, setton requested changes

2020-12-10 11:23 UTC, setton commented on source/ada/lsp-ada_handlers.adb
> +      --  the results to response. If a rename problem is found, return a
(clarification): this says "if a problem is found, return a response with an error": at first I thought this should be transformed into a function that actually returns the error... I suggest to clarify this by explaining which mechanism is being used to return the error to the user.

2020-12-10 11:23 UTC, setton commented on source/ada/lsp-ada_handlers.adb
> +         --  Analysis unit of the reference that is being added to Response.
(style): single-line comments shouldn't end with `.`

2020-12-10 11:23 UTC, setton commented on source/ada/lsp-ada_handlers.adb
> +         --  Add a reference to Response if it has not been added yet.
(see above)

2020-12-10 11:23 UTC, setton commented on source/ada/lsp-ada_handlers.adb
> +               span    => LSP.Messages.Span'
how about introducing an utility function to transform a Langkit Sloc_Range to a LSP span?

2020-12-10 11:23 UTC, setton commented on source/ada/lsp-ada_handlers.adb
> +               Response.result.changes.Insert
(style): no need for a line break here

2020-12-10 11:23 UTC, setton commented on source/ada/lsp-ada_handlers.adb
> +         Cursor_1 : Unit_Slocs_Maps.Cursor;
(style): name the cursors with something more meaningful, for instance `Unit_Cursor` and `Sloc_Cursor` ?

2020-12-10 11:23 UTC, setton commented on source/ada/lsp-lal_utils.adb
> +      return To_Unbounded_Text (From_UTF8 (To_UTF_8_String (Item)));
It's dangerous to return a String when the string might be giant: add a warning to say we shouldn't pass a buffer to this function.

2020-12-22 09:29 UTC, AnthonyLeonardoGracio approved these changes

2021-01-12 16:56 UTC, setton approved these changes

2021-01-12 16:56 UTC, merged