U304-005 Add basic support for preprocessor directives
AdaCore/ada_language_server pull request #626
Opened 2021-03-10 18:15 UTC by setton

For now, we do not support an actual preprocessor, but work
in a degraded mode where the "#if" branch of preprocessing is
always chosen.

This allows responding to requests in cases where simply
"ignoring all preprocessing" is not sufficient because it
results in non-valid syntax, for instance

     #if A
        procedure foo (
     # else
        procedure foo (
     # endif

We do this by intercepting buffers before they are sent
to Libadalang, and preprocess on-the-fly.

This also adds support for working with non-LF line terminators:
the line terminators are changed to LF as part of the
preprocessing.

2021-03-16 22:01 UTC, reznikmm requested changes
1. Why do we need to change line terminator? I'm afraid this could confuse the client. If server sends '\n' instead of actual line ending in the workspace edit request, the source could become a mess on the client side.
2. Also I'm not sure if the ALS should do source preprocessing instead of LAL. With this approach any server side modifications will not work. For instance
   *  Format document/format selection will not work, because server will send empty lines instead of `#els` parts and directives. So client will just clean these line up.
   * Refactoring will not work inside `#els` parts
3. I'm not sure that incremental text updates from the client (in `#els` parts) won't break server, because server won't find text position from the notification.

2021-03-17 09:19 UTC, setton commented on source/ada/lsp-preprocessor.adb
> +            Currently_Preprocessing := False;
yes, but actually LAL simply ignores it. I'll change so that it's clearer.

2021-03-17 09:26 UTC, setton commented
> 1. Why do we need to change line terminator? I'm afraid this could confuse the client. If server sends '\n' instead of actual line ending in the workspace edit request, the source could become a mess on the client side.

I was thinking that we need to change the line terminators before sending to GS, since GS converts any file from disk to using LF whilst in buffer. But in fact I will move this part to the client, this seems to be what's expected by the server - at least that's my interpretation of this new field in the WorkspaceEditCapabilities

         /**
	 * Whether the client normalizes line endings to the client specific
	 * setting.
	 * If set to `true` the client will normalize line ending characters
	 * in a workspace edit to the client specific new line character(s).
	 *
	 * @since 3.16.0
	 */
	normalizesLineEndings?: boolean;

So, I'll make the change.

> 2. Also I'm not sure if the ALS should do source preprocessing instead of LAL. With this approach any server side modifications will not work. For instance
>    
>    * Format document/format selection will not work, because server will send empty lines instead of `#els` parts and directives. So client will just clean these line up.
>    * Refactoring will not work inside `#els` parts

Agreed but unfortunately LAL has no plan right now to support source preprocessing. We can keep discussing this with them in the TN but we need something to fix the customer's case.

Right now LAL ignores completely any preprocessing directive, so this patch is an improvement in that at least it will allow users to navigate in the presence of refactoring that breaks the syntax.

> 3. I'm not sure that incremental text updates from the client (in `#els` parts) won't break server, because server won't find text position from the notification.

This should work: what we're doing is intercepting the buffer before it gets sent to LAL, but the support of incremental text is upstream from this.

2021-03-17 09:30 UTC, reznikmm commented
> I will move this part to the client,
We need it on the client side anyway, to protect GS from `clangd` (and potential others servers).

2021-03-17 21:41 UTC, setton commented
following up under https://github.com/AdaCore/ada_language_server/pull/640

2021-03-17 21:41 UTC, closed without merging

2021-03-17 21:41 UTC, setton commented
following up under https://github.com/AdaCore/ada_language_server/pull/640