U308-004 When receiving an exception, always send a response
AdaCore/ada_language_server pull request #630
Opened 2021-03-12 21:41 UTC by setton

Add code to send an empty response when the exception is due
to "invalid Ada": we don't want to send a backtrace in this case,
but clients are still interested to get the response to the request.

2021-03-13 06:27 UTC, reznikmm requested changes
I think we should use `LSP.Error_Decorators` instead. Each request may have distinct format of an empty `result`. That's why Error_Decorator is invented.

2021-03-13 09:12 UTC, setton commented
Good point, I’ll take a look. 

> On 13 Mar 2021, at 06:28, Maxim Reznik ***@***.***> wrote:
> 
> ﻿
> @reznikmm requested changes on this pull request.
> 
> I think we should use LSP.Error_Decorators instead. Each request may have distinct format of an empty result. That's why Error_Decorator is invented.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-13 12:11 UTC, setton commented
> I think we should use `LSP.Error_Decorators` instead. Each request may have distinct format of an empty `result`. That's why Error_Decorator is invented.
> Also I'm not sure that sending `Is_Error=>True` without any explanation in the `error` field is a good idea.

Done, moved the logic to Error_Decorators. It works.

2021-03-14 09:21 UTC, reznikmm approved these changes

2021-03-14 09:27 UTC, merged