U610-067 Pretty printer options
AdaCore/ada_language_server pull request #748
Opened 2021-07-22 13:01 UTC by ogorodnik

Using the corresponding project that a file belongs to
 get the options.

2021-07-23 08:09 UTC, AnthonyLeonardoGracio requested changes

2021-07-23 08:09 UTC, AnthonyLeonardoGracio commented on source/ada/lsp-ada_contexts.adb
> +      for Item of Options.all loop
Lacking comments. Put a comment to say that we are counting valid options here for instance, people don't want to analyze each loop in your code

2021-07-23 08:09 UTC, AnthonyLeonardoGracio commented on source/ada/lsp-ada_contexts.adb
> +      Validated := new GNAT.Strings.String_List (Options'First .. Last);
"Validated_Options" would be even better

2021-07-23 08:09 UTC, AnthonyLeonardoGracio commented on source/ada/lsp-ada_contexts.ads
> +   procedure Get_PP_Options
Comment

2021-07-23 08:09 UTC, AnthonyLeonardoGracio commented on source/ada/lsp-ada_handlers.adb
> +   function Get_Project
LSP.Ada_Documents seems a better package to put that function (might be reused somewhere else in the future)

2021-07-23 08:09 UTC, AnthonyLeonardoGracio commented on source/ada/lsp-ada_handlers.adb
> +   --  Retrieve the project that the file belongs to. Root project is returned
You should say what it does for aggregate projects (that's the purpose of your function)

2021-09-08 08:42 UTC, reznikmm commented
closing till we get real issue with this

2021-09-08 08:42 UTC, closed without merging