UC15-036 Add `gpr-unit-provider` dependency
AdaCore/ada_language_server pull request #978
Opened 2022-06-13 05:59 UTC by reznikmm

2022-06-13 06:14 UTC, setton requested changes

2022-06-13 06:14 UTC, setton commented on gnat/lsp_server.gpr
> +with "gpr_unit_provider.gpr";
we only need it once :)

2022-06-16 12:50 UTC, setton submitted a review, later dismissed

2022-06-17 06:44 UTC, reznikmm commented
I've added `GPR_UNIT_PROVIDER_BUILD=debug` to `Makefile`. Could you review again?

2022-06-17 11:43 UTC, AnthonyLeonardoGracio approved these changes

2022-06-19 08:57 UTC, merged